language: java
script: cd master && mvn clean verify
branches:
  only:
  - develop
jdk:
- oraclejdk7
before_install:
- rvm install 2.0.0
- gem install travis-custom-deploy
after_success:
- travis-custom-deploy sftp de.prob2.updatesite/target/repository/
env:
  global:
  - secure: SGU9V3b72o1cf3F49E0xhe4YBjafh0GEZzp3vQKPRMsTObR28rRBx6dpA7PzdgUHyzhP4kyTq4OwJAaSjlBPQXX5MlYcXHcDMEnA4DLLT6VpEscv9K2KYu+2DLbhW0TyFx+7vxyBst3ZX2bfw7VTcoo2vgo5b7GNYpkIZQu6cxo=
  - secure: DrQLIoZ82HLaR0TxaZn8Zan/D3nV8FApMkq6I36cmsOidvIIUxdBGRb9G5WcwZJqZ8CaceK04z0eHprlNCpGoKmBdn6pxgdj5lZPedULcbsSO8q2Hw/06VlXrEBlWKItrfqkN8T/W/Ul7LdUs+lzIniOl8zYmxIMiYP4RtDmXG0=
  - secure: LDZketS8yG48LA7OKywTtllYFu5l+cYkjRMMoZ8lTVL4OXtHeZ8ntzrI3EG62PccoDI03W48w0LQJ6/bJyIk0JymPZpEKLmocXwpW7F+ac1FYPHLJ/uo0ZRN7hOSHsw9hyBg90pklz574k0PDdbI3rldVidd1TIuulvwvcY8HHw=
  - secure: SsM0SVXeKwJR3prVrVUDBS7TzpTyc3RX8iCctULn020ihIeP+wzwAUYyMRrv004usgAQXFD7fWQVXcU+iUS8yEExLk34gDwywASPvz1sAHJZjYEt8YIJCVaFFCZzIF4sO9mYNU0P8Bb/GtWW3t3lD1REI04XBniSZ5DiETQUq1M=
